name: oauth
version: 0.3.1
author: Owen Shepherd <*@owenshepherd.net>
        Matthew Butler <butler.matthew@gmail.com>
description: An implementation of OAuth 1.0a per RFC 5849
homepage: https://github.com/oshepherd/oauth.dart
dependencies:
  crypto: '^2.0.0'
  pointycastle: '^0.10.0'
  http: '^0.11.3'
dev_dependencies:
  shelf: '^0.6.5'
  test: '^0.12.0'
